{
  "kind": "Deployment",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "dbsync",
    "namespace": "default",
    "selfLink": "/apis/extensions/v1beta1/namespaces/default/deployments/dbsync",
    "uid": "e4ff5b4a-e7e6-11e7-94da-42010a9a020e",
    "resourceVersion": "15979",
    "generation": 1,
    "creationTimestamp": "2017-12-23T13:40:52Z",
    "labels": {
      "app": "dbsync",
      "version": "v1"
    },
    "annotations": {
      "deployment.kubernetes.io/revision": "1"
    }
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "app": "dbsync",
        "version": "v1"
      }
    },
    "template": {
      "metadata": {
        "name": "dbsync",
        "creationTimestamp": null,
        "labels": {
          "app": "dbsync",
          "version": "v1"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "dbsync",
            "image": "dheerajbhadani/dbsync:v1",
            "resources": {},
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "IfNotPresent",
            "securityContext": {
              "privileged": false
            },
            "volumeMounts": [
	    {
              "name": "dbsync-persistent-storage",
              "mountPath": "/home/dheerajbhadani/testfiles/"
            }
	    ]
          }
        ],
	"volumes":[
        {
            "name":"dbsync-persistent-storage",
            "gcePersistentDisk": {
                "pdName":"dbsync-test",
                "fsType":"ext4"
            }
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "securityContext": {},
        "schedulerName": "default-scheduler"
      }
    },
    "strategy": {
      "type": "RollingUpdate",
      "rollingUpdate": {
        "maxUnavailable": 1,
        "maxSurge": 1
      }
    }
  },
  "status": {
    "observedGeneration": 1,
    "replicas": 1,
    "updatedReplicas": 1,
    "readyReplicas": 1,
    "availableReplicas": 1,
    "conditions": [
      {
        "type": "Available",
        "status": "True",
        "lastUpdateTime": "2017-12-23T13:40:52Z",
        "lastTransitionTime": "2017-12-23T13:40:52Z",
        "reason": "MinimumReplicasAvailable",
        "message": "Deployment has minimum availability."
      }
    ]
  }
}
